#!/bin/bash

trash_path=~/.trash # trash folder location
log_path=~/.trash.log
file_name=""
cur_path=""
origin_path=""
output_path=""

# is log exists
if [[ ! -e $log_path ]] ; then
        echo "File opening error: log doesn't exists!"
        exit 1
else
        echo "Log file opened successful!"
fi

while IFS= read -r line
do
	file_name=$(echo $line | awk '{ print $1 }')
	if [[ $file_name != $1 ]] ; then
		continue
	fi
	cur_path=$(echo $line | awk '{ print $5 }')
	origin_path=$(echo $line | awk '{ print $3 }')
	echo $cur_path" : do you like to restore $file_name to $origin_path? (y/n)"
	read INPUT < /dev/tty
	case $INPUT in
		"y")
			if [[ -e $origin_path ]] ; then
				if [[ -e "$origin_path/$file_name" ]] ; then
					new_file_name=""
					echo "Please, enter different filename: "
					read new_file_name < /dev/tty

					if [[ -e "$origin_path/$new_file_name" ]] ; then
						echo "You entered also existing filename!"
						exit 1
					fi
					output_path="$origin_path/$new_file_name"
				else
					output_path="$origin_path/$file_name"
				fi
			else
				output_path= "~/$file_name"
			fi
			ln $cur_path $output_path
			rm -rf $cur_path
			echo "File was untrashed to $output_path"
			;;
		"n")
			continue
			;;
		*)
			echo "Incorrect input"
			exit 1
			;;
		esac
done < $log_path