#!/bin/bash

while true
do
    read LINE
    case $LINE in 
        +)
            kill -USR1 $(cat pid)
            ;;
        "x")
            kill -USR2 $(cat pid)
            ;;
        TERM)
            kill -TERM $(cat pid)
            ;;
        *)
            :
            ;;
    esac
done
