#!/bin/bash

echo $$ > pid
selector=1
result=1

usr1() {
    echo "Change to usr1"
    mode="usr1"
}

usr2() {
    echo "Change to usr2"
    mode="usr2"
}

term() {
    echo "Change to term"
    mode="term"
}

mode="usr1"
trap "usr1" USR1
trap "usr2" USR2
trap "term" TERM

while true
do
    case $mode in
        "usr1")
            let result=$result+2
            echo "result = $result"
            ;;
        "usr2")
            let result=$result\*2
            echo "result = $result"
            ;;
        "term")
            echo "result = $result"
            echo "exit"
            exit 0
            ;;
    esac
    sleep 1
done
